version: '3.3'
services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/

#version: '3.3'
#services:
#  db:
#    image: postgres:13.0-alpine
#    volumes:
#      - pg_data:/var/lib/postgresql/data/
#    env_file:
#      - .env
#  web:
#    image: hitfortime/foodgram:latest
#    restart: always
#    volumes:
#      - static_value:/app/static/
#      - media_value:/app/media/
#    depends_on:
#      - db
#    env_file:
#      - .env
#  frontend:
#    image: hitfortime/foodgram-front:latest
#    volumes:
#      - ../frontend/:/app/result_build/
#  nginx:
#      image: nginx:1.19.3
#      ports:
#        - "80:80"
#        - "443:443"
#      depends_on:
#        - web
#      volumes:
#        - ./nginx.conf:/etc/nginx/conf.d/default.conf
#        - ../frontend/build:/usr/share/nginx/html/
#        - ../docs/:/usr/share/nginx/html/api/docs/
#        - static_value:/var/html/static/
#        - media_value:/var/html/media/
#volumes:
#  static_value:
#  media_value:
#  pg_data: